- type: job
  id: ProphetTAP
  name: job-name-prophet
  description: job-description-prophet
  playTimeTracker: JobProphetTAP
  weight: 100
  startingGear: ProphetGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconProphet"
  supervisors: job-supervisors-prophet
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:CharacterSpeciesRequirement
      species:
        - Moth
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-prophet
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - Tradeband
          - OldTaypani
        addUnderstood:
          - Tradeband
          - OldTaypani
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - Families
  - Arabet
  - Alseik
  - AlseikServile
  - Thukker
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - External
  - Captain # Frontier

- type: startingGear
  id: ProphetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBodysuit
    back: ClothingBackpackSatchelLeatherFilledNCWL
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterHardsuitArabet
    id: ProphetPDA
    ears: ClothingHeadsetFamilies
